export const featureFlags = {
  // New branding - all on for stakeholder demo
  newBranding: true,
  newTypography: false,
  newTables: false,
  newBubble: false,
  newTopNavbar: false,
  newLeftSidebar: true,
  newRightPanel: false,
  newMainStage: true,
  newGradientBackground: false,
  newResizeablePanels: true,
  newChatInput: true,
  plays: false,
  builtByOther: false,
  themes: true,
  themeSelector: false,
  showThemeDebugger: false,
  conversationPin: false,
  conversationRename: false,
  conversationWrap: false,
  conversationCollapsible: false,
  conversationTimestamps: false,
  conversationMenu: false,
  workspaces: false,
  // Restaurant concept flags - Top Nav: all off
  restaurantBreadcrumbs: false,
  restaurantTopNavButtons: false,
  restaurantTopNavSearchBar: false,
  // Restaurant home view sections - all on except Quick Actions
  restaurantSubtitle: true,
  restaurantAtAGlance: true,
  restaurantJumpBackIn: true,
  restaurantQuickActions: false,
  restaurantRunAgents: true,
  // Restaurant navigation - on
  restaurantLocations: true,
};