export const featureFlags = {
  newBranding: false,
  newTypography: false,
  newTables: false,
  newBubble: false,
  newTopNavbar: false,
  newLeftSidebar: false,
  newRightPanel: false,
  newMainStage: false,
  newGradientBackground: false,
  newResizeablePanels: false,
  newChatInput: false,
  plays: false,
  builtByOther: false,
  themes: false,
  themeSelector: false,
  showThemeDebugger: false,
  conversationPin: false,
  conversationRename: false,
  conversationWrap: false,
  conversationCollapsible: false,
  conversationTimestamps: false,
  conversationMenu: false,
  workspaces: false,
  // Restaurant concept flags
  restaurantBreadcrumbs: false,
  restaurantTopNavButtons: false,
  restaurantTopNavSearchBar: true,
  // Restaurant home view sections
  restaurantSubtitle: true,
  restaurantAtAGlance: true,
  restaurantJumpBackIn: true,
  restaurantQuickActions: true,
  restaurantRunAgents: true,
  // Restaurant navigation
  restaurantLocations: true,
};