export const featureFlags = {
  newBranding: false,
  newTypography: false,
  newTables: false,
  newBubble: false,
  newTopNavbar: false,
  newLeftSidebar: false,
  newRightPanel: false,
  newMainStage: false,
  newGradientBackground: false,
  newResizeablePanels: false,
  plays: false,
  builtByOther: false,
  themes: false,
  themeSelector: false,
  showThemeDebugger: false,
  conversationPin: false,
  conversationRename: false,
  conversationWrap: false,
  conversationCollapsible: false,
  conversationTimestamps: false,
  conversationMenu: false,
  workspaces: false,
};